### ISSUE TITLE
Time has no end. 

### ISSUE THREAD

**Issue by Zbig281** [LiF-x/Healer#1]
I suggest changing getRealTime to getSimTime in the code. Real time is more buggy and problematic. 
![image](https://github.com/LiF-x/Healer/assets/31387906/a97da77d-d6ef-4eae-b2a1-9614767ab6a9)
![image1](https://github.com/LiF-x/Healer/assets/31387906/8cbd9243-4fde-4cc6-bde1-21af14e55369)
I fixed the problem by changing everywhere to getSimTime .

**Comment by Mj0ed** [comment]
Please create a pull request with the code that you wish to introduce as a patch

**Comment by ChristopheRoblin** [comment]
closing

**Comment by Mj0ed** [comment]
closing
